const TOGGLE_LOADER = 'TOGGLE_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';
const USER_LOGOUT = 'USER_LOGOUT';
const SET_USER = 'SET_USER';
const SET_THEME = 'SET_THEME';
const SET_LANGUAGE = 'SET_LANGUAGE';

export {
  TOGGLE_LOADER,
  HIDE_LOADER,
  USER_LOGOUT,
  SET_USER,
  SET_THEME,
  SET_LANGUAGE,
};
